Redmine 10917
eayunstack/trove pull request #40
Opened 2017-09-11 08:04 UTC by jinhui-li

add trove pass database monitoring features

2017-09-12 02:37 UTC, huntxu commented on trove/cmd/guest.py
> +    openstack_cfg.StrOpt('monitoring_power', default='on',
如果这是一个开关，那更应该用Boolean，省去每次比较字符串的麻烦

2017-09-12 02:42 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/manager.py
> +        LOG.debug("Polling monitoring database.")
这里看起来像只是为了打印一行日志于是把`self.app.metering_loop()`包了一层，但是log完全可以放到具体的`self.app.metering_loop()`里面然后`FixedIntervalLoopingCall()`里直接用就是了

2017-09-12 02:45 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/manager.py
> +        filepath = '/etc/trove/trove-guestagent-monitoring.ini'
用常量或者配置项

2017-09-12 02:45 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/manager.py
> +        config.read(open(filepath, 'rw'))
这个文件开了但是不保证关。用`with`

2017-09-12 02:46 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/manager.py
> +            config.set('Timer', option, value)
这里没对传过来的数组做任何检查？是别的地方有过过滤？

2017-09-12 02:50 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/monitor.py
> +    QPS = serverStatus['opcounters']['query']
变量用小写

2017-09-12 02:55 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/monitor.py
> +        serverStatus = admin_client.admin.command(bson.son.SON('serverStatus'))
这里是否总是能够保证`serverStatus`返回正常的值？如果不行的话需要异常处理。如果serverStatus不一定总是返回固定格式，底下对它的使用也需要判断后才用

2017-09-12 02:57 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/service.py
> +        if self.conf.monitoring_power == 'off':
这个app并没有对应的配置项啊？

2017-09-12 02:58 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/service.py
> +        delta = ts - self.last_report
第一次进的时候self.last_report不存在，需要在`__init__`里先定义某人值，这里做下判断

2017-09-12 02:59 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/service.py
> +        report_interval = self.conf.report_interval
这个app也没有这个配置项，`self.conf`是manager的，不是app的

2017-09-12 02:59 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/service.py
> +        server_type = 'mongodb'
常量

2017-09-12 03:01 UTC, huntxu commented on trove/guestagent/datastore/experimental/redis/manager.py
> +        self.metering_loop.start(interval=measure_interval)
这整段代码我上面才看过，包括底下两个函数。如果全部都是一模一样的代码，应该考虑合并到一起。python可以轻松多继承

2017-09-12 03:10 UTC, huntxu commented on trove/guestagent/datastore/experimental/redis/monitor.py
> +                transactionQPS += int(self.get_calls(info[key]))
以上这些`get_calls`相关的一系列内容逻辑都是一样的，可以考虑抽象一下代码。

另外`key`的列表相对固定，另开文件当作常量储存吧，或者放到同一个文件里问题也不大。

2017-09-12 03:11 UTC, huntxu commented on trove/guestagent/datastore/experimental/redis/service.py
> +        notifier.info(context, 'trove_database.meter', data)
这整段代码我上面也才看过，区别只是counter获取的函数

2017-09-12 03:12 UTC, huntxu commented on trove/guestagent/datastore/mysql_common/manager.py
> +
这是第三份复制了

2017-09-12 03:14 UTC, huntxu commented on trove/guestagent/datastore/mysql_common/monitor.py
> +def get_item(data_dict, item):
看不明白为什么其他两个是个monitor类，到mysql这里变成全是独立函数了

2017-09-12 03:15 UTC, huntxu commented on trove/guestagent/datastore/mysql_common/service.py
> +        notifier.info(context, 'trove_database.meter', data)
同第三份复制

2017-09-13 07:46 UTC, huntxu commented
重新组织你的git commit历史，不是把所有review的修改都独立成新的commit。应该修改你原来的commit。

2017-09-14 03:56 UTC, 2hf commented on trove/guestagent/datastore/experimental/mongodb/monitor.py
> +# Copyright 2013 OpenStack Foundation
既然是你自己新增的文件，这里的Copyright应该改为易云吧？

2017-09-14 04:04 UTC, huntxu commented
整体感觉上，采集和定时报告数据的内容应该放在App里面更好，不应该放在Status里，@zhaochao, @2hf 我不太确定。

如果上面那句成立，那思路应该是下面这样：
1. 定义一个基类MeteringApp，里面完成循环采集和报告的工作，使用self.get_counter这个abstract_method，定义一个None类型的service_type或者同样使用abstract_method。
2. 每个类型的数据库再定义一个XXMeteringApp，定义和该类型相关对应的get_counter，以及对应的service_type
3. 让每个类型的数据库App继承第2步中定义的App，而非现在的object

2017-09-14 04:41 UTC, 2hf commented on trove/guestagent/datastore/experimental/redis/commandstat.py
> +# Copyright 2013 OpenStack Foundation
same issue with copyright

2017-09-15 08:31 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/service.py
> +        counter = monitoring.monitoring_mongodb()
直接把`monitoring_mongodb()`的内容放到`get_counter()`这个函数里面，以及它所需要的辅助函数放到这个类里面（这个类只展现`get_counter`）。不再需要各种`monitor`相关的东西。以下对其他类型的也是如此，以后有扩展也是如此。

2017-09-15 08:34 UTC, huntxu commented on trove/guestagent/datastore/service.py
> +    last_report = 0
这个变量应该是成员变量不应该是类变量，在这里需要在`__init__`里定义才是。注意如果你这里定义了__init__的话，子类记得要用super调一下这个类的`__init__`。

2017-09-15 08:56 UTC, 2hf commented on trove/guestagent/datastore/experimental/redis/service.py
> +        "Returns the number of keys in the current database"
triple double-quotes？

2017-09-15 08:57 UTC, 2hf commented on trove/guestagent/datastore/manager.py
> +        '''This method is to modify the configuration,
triple double-quotes？

2017-09-15 09:13 UTC, jinhui-li commented on trove/guestagent/datastore/service.py
> +    last_report = 0
那RedisApp和RedisMeteringApp都需要用super调一下父类的__init__?
mongo和mysql同上

2017-09-15 09:15 UTC, jinhui-li commented on trove/guestagent/datastore/experimental/mongodb/service.py
> +        counter = monitoring.monitoring_mongodb()
当时是怕采集数据的方法过长,想着新写一个文件,这个可以不改吗

2017-09-15 09:16 UTC, huntxu commented on trove/guestagent/datastore/service.py
> +    last_report = 0
有重载`__init__`的地方需要`super`

2017-09-15 09:18 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/service.py
> +        counter = monitoring.monitoring_mongodb()
不改那你就直接把这个类放到那个独立文件里面，也同样不需要monitor相关的内容。

2017-09-15 09:21 UTC, huntxu commented on trove/guestagent/datastore/service.py
> +        This is a base class to do a looping task, the main work
第一句注释欠妥，这个类并不做具体looping的工作，只是定义了每次循环所要执行的内容，具体执行looping的是在manager。

2017-09-15 09:24 UTC, huntxu commented on trove/guestagent/datastore/service.py
> +    def metering_loop(self):
到这里看起来，metering_loop和metering_notification两个函数完全可以放在manager里面，循环在manager里似乎更好一点。唯一变化就是metering_notification里面的counter和service_type两处需要修改而已。

2017-09-15 09:29 UTC, jinhui-li commented on trove/guestagent/datastore/service.py
> +    def metering_loop(self):
不要MeteringApp这个class了?

2017-09-15 09:37 UTC, huntxu commented on trove/guestagent/datastore/service.py
> +    def metering_loop(self):
仍然需要，MeteringApp这个类有个重点就是用来定义get_counter这个abstractmethod和servicetype这个假变量的。也就是说是你以后扩展到其他类型数据库的一个模版。每个需要加监控的数据库类型，只需要实现get_counter和对service_type赋值就好。

所以接上一段，你这改动就可以细分成以下逻辑：
1. 整个定时报告的框架，和一个模版的app
2. 运行时修改配置文件的重新启动定时器的改动
3. (及更多) 每个类型的数据库对那个框架进行实现。

这样子以后回顾代码才不至于乱。但是无论你把metering_loop放在哪里，都需要注意，要么是不一定所有app都会有metering_loop，要么是不一定每个app都会有get_counter。这个也需要考虑

2017-09-15 09:37 UTC, zhaochao commented on trove/guestagent/datastore/service.py
> +    def metering_loop(self):
对，metering_loop 和 metering_notification 是应该放到 manager 里。

对 MeteringAPP 这个，倒是可以考虑像 AppStatus 一样，不作为 App 的基类，而是初始化一个实例作为 App 的属性。App 这个类其实只实现对底层数据库服务具体操作。

2017-09-15 10:08 UTC, jinhui-li commented on trove/guestagent/datastore/service.py
> +    def metering_loop(self):
大概懂了,结合hunt上一条review:
1. 我新建一个文件放xxxMeteringApp类,主要负责server_type和get_counter具体实现
2. 基类的service里新建MeteringApp类,定义get_counter和假变量server_type
3. 基类的manage放looping任务,组织数据,发送那些
4. 这样基本不会涉及到各个数据库类型的manage和service的修改

2017-09-19 10:29 UTC, 2hf commented on trove/guestagent/datastore/manager.py
> +FILEPATH = '/etc/trove/trove-guestagent-monitoring.ini'
这个能不能放到cfg中……比如CONF.FILEPATH？这样写在代码里没办法配置吧？

2017-09-29 02:39 UTC, chenpengzi commented on etc/trove/trove-guestagent-monitoring.ini
> +report_interval = 300
no newline at end of file。

2017-09-29 03:05 UTC, fabian4 commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        innodb_buffer_pool_size = self.get_item(mysql_status,
这里不应该用mysql_status　而是应该用mysql_variables，　mysql_status将返回空，那么做计算的时候不能获取到数据

2017-09-29 06:12 UTC, fabian4 commented on trove/guestagent/datastore/experimental/redis/meteringapp.py
> +            qps = info['total_commands_processed']
这里qps并没有设置默认值，因此是否说明total_commands_processed一定在info中存在，如果一定存在，这里就没有必要添加if ?

2017-09-29 06:12 UTC, fabian4 commented on trove/guestagent/datastore/experimental/redis/meteringapp.py
> +            total_connections_received = \
同上

2017-09-29 08:06 UTC, fabian4 commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        try:
这里的try...except是否就是避免key不存在？　如果是的话，能否改成:
item_value = [ item_value if item in data_dict else 0][0]  ？

2017-09-29 08:24 UTC, fabian4 commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        try:
item_value = [data[item] if item in data_dict else 0][0]

2017-10-18 02:31 UTC, zhaochao requested changes

2017-10-18 02:31 UTC, zhaochao commented on etc/trove/trove-guestagent-monitoring.ini
> +monitoring_power_on = True
配置组本身是 eayun_monitor ，配置项就不用加 monitor 了，直接用 eanbled 之类？

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +                LOG.exception(_("Error getting MongoDB status."))
_ 未定义，类似问题跑一下 pep8/pyflakes/pylint 之类的工具可以自行检查。

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/api.py
> +        return self._call("guest_eayun_monitor_modify", AGENT_HIGH_TIMEOUT,
超时时间，感觉应该用 AGENT_LOW_TIMEOUT ？

目前预期的 low 和 high timeout 分别是 5 和 150 秒，正常更新 monitor 5 秒应该足够了。如果重启 looping 需要等待的话，可以考虑用 high timeout 。

2017-10-18 02:31 UTC, zhaochao commented on trove/common/api.py
> +                       action="guest_eayun_monitor_modify",
guest_eayun_monitor_update ？

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +                serverStatus = admin_client.admin.command('serverStatus')
这里完全可以在 MongoDBAdmin 里增加一个获取 serverStatus 的方法，之后 import 进来直接用就可以了。

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/experimental/redis/meteringapp.py
> +    def countcommand(self, commandstatlist, info):
countcommands ?

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/experimental/redis/meteringapp.py
> +    def countkey(self, db_list, info):
countkeys ?

计算 redis 里所有 db 里 key 的总数，用一次循环就可以了，没有必要先用循环成一个 db_list ，然后对 db_list 遍历一次。

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/experimental/redis/meteringapp.py
> +                (string.atof(keyspace_hits) + string.atof(keyspace_misses))
keyspace_hits + keyspace_misses 没必要算 2 遍。

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/experimental/redis/meteringapp.py
> +
~上面这些 countcommand 和 countkey 的问题有点类似，这里完全可以只遍历一遍 info 把所有的 command 相关的数据做一次分类整理。按现在的实现，每调用一次 countcommand 都会遍历一次 info 。~

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/experimental/redis/service.py
> +        self.metering = meteringapp.RedisMeteringApp(self.admin)
这里如果更改了 redis 的 requirepass ，会导致 admin client 不可用，需要重新实例化 admin client ，参考 #37 。

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +                config.set('eayun_monitor', option, value)
1. 更新定时任务这个 api 在接收用户请求需要进行基本的合法检查；
2. 在 guest_eayun_monitor_modify 这里，应该再作进一步的处理，比如如果配置项没有实际性的改动，则可以不更新配置文件以及重启定时任务；

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        self.mysql_admin = mysql_admin
从 MysqlAdmin 的实现看，这里应该只需要传递 mysql_admin 就可以。

另外一个问题是，从 mongo 、redis 、mysql 三个 meteringapp 看，传递 admin client 是相同的，应该考虑放到基类里去。

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        return item_value
get_item 这个函数看起来没什么必要，直接 dict 的 get 方法。

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        return data_dict
上面 3 个方法，除了 sql 语包之外，别的都一样，可以考虑合并成一个方法。

另外， client.execute 执行上面 3 条 sql 语句都会返回的是一个由 2 个元素的 tuple （Variable_name, Value) 组成的 iterable 对象（ResultProxy），所以用 for 循环时，可以一次性把 Valuable_name 和 Value 取出来。
当然因为 ResultProxy 对象是 iterable ，所以直接生成 dict 也是可以。

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +            slave_status = self.get_slave_status(client)
前面评论里提过，这里应该直接用 mysql_admin 就可以了， mysql_admin 实例化后本身就是一个 mysql client ，可以直接执行 SQL 语句。

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        if string.atof(innodb_buffer_pool_pages_data) != 0:
才注意用了很多 string.atof ，但是目前没发现不直接用 float() 的理由。

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +                                string.atof(Qcache_inserts))
前面也出现过类似的做法，像这种计算结果后面会用到，应该都提前计算，用一个变量保存结果，后面直接使用就可以了。

2017-10-18 02:31 UTC, zhaochao commented on trove/instance/service.py
> +        LOG.debug("body: %s", body)
应该对 body 进行基本的检查，比如是不是一个 dict ？

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +        notifier.info(context, 'trove_database.meter', data)
从配置项看 measure_interval 和 report_interval 分别是采集和发起通知的时间间隔，但是从 metering_loop 的实现看，其实采集是在 metering_notification 时发生的，这样前面 2 个 interval 实际上只有 report_interval 有意义。

这里应该和原本的设计不一样，需要重新实现。

2017-10-18 02:31 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +        self.metering_loop_task.start(interval=measure_interval)
直接 stop 的话，会有一次定时任务被跳过，比如 300 秒一次任务，在第 299 秒时修改 interval ，改成 360 秒，这样的话，1秒之后的那次任务就跳过。

这样需要明确重启 loopingcall 的行为。

2017-10-18 06:56 UTC, jinhui-li commented on trove/guestagent/datastore/experimental/redis/meteringapp.py
> +
if key in info,这样会遍历info?

2017-10-18 07:04 UTC, 2hf commented on trove/guestagent/datastore/experimental/redis/meteringapp.py
> +    def countcommand(self, commandstatlist, info):
def count_conmands(self, cmd_stat_list, info)
类似这样，遵循一下Python中的蛇形命名规范……可以参考 http://www.jianshu.com/p/e3ed63f67e3b

2017-10-18 07:35 UTC, zhaochao commented on trove/guestagent/datastore/experimental/redis/meteringapp.py
> +
噢，这里可能是我一开始理解得不对，if key in info 不是遍历，那这里不算是问题吧。

commandstat 倒是可以改改，直接这么用，写起来太长，而且关键字重复。改成类似：
```
commandstats = {
    ...,
    'hyperloglog': [
        'cmdstat_pfadd',
        'cmdstat_pfcount',
        'cmdstat_pfmerge'
    ],
    ...
}
```

2017-10-18 09:26 UTC, 2hf commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        if string.atof(innodb_buffer_pool_pages_data) != 0:
string.atof(s) 在Python 2.0中就不推荐使用了，用float()确实会更好

2017-10-20 06:50 UTC, zh-f requested changes

2017-10-20 06:50 UTC, 2hf commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +            for key1, key2 in zip(ksylist, curdlist):
key1，key2…… ksylist……nitpick，命名稍微不是很好…… 😂

2017-10-20 06:50 UTC, 2hf commented on trove/guestagent/datastore/experimental/mongodb/service.py
> +        """"Get the database serverstatus"""
nitpick again……I prefer "server_status" 😃

2017-10-20 06:50 UTC, 2hf commented on trove/guestagent/datastore/experimental/redis/meteringapp.py
> +        # connected_clients
这里连同后面的注释，包括前面的 ``#keys`` 没有必要吧，你变量的命名足够了……

2017-10-20 06:50 UTC, 2hf commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        # innodb_buffer_pool_size
这里和下面的几个注释也是同样的，就是把变量名复制了一遍……没什么意义吧。

2017-10-23 07:34 UTC, zhaochao requested changes

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +            for key1, key2 in zip(ksylist, curdlist):
嗯，是不太好，变量名尽量有明确的含义。

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/experimental/mongodb/service.py
> +        """"Get the database serverstatus"""
嗯，用 server_status 比较，和 `MongoDBAdmin` 其它方法的命名也能保持一致。

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +        mongoDBAdmin = service.MongoDBAdmin()
import 应该放到文件开头去，直接从 trove.guestagent.datastore.experimental.mongodb.service 里把 MongoDBAdmin import 进来。

另外这里也没什么特别必要把实例化之后的 MongoDBAdmin 作为一个变量，直接调用实例的 server_status 方法把数据拿到就可以了。

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/experimental/redis/meteringapp.py
> +from commandstat import commandstats
[relative-import] Relative import 'commandstat', should be 'trove.guestagent.datastore.experimental.redis.commandstat' [python/pylint]

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/experimental/redis/meteringapp.py
> +        # connected_clients
+1

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +        self.data = {}
直接用 data 不太好，需要更明确一些，比如 metering_data ？

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +        self.metering_notification_task.start(interval=self.report_interval)
这 2 个 loopingcall 的 start ，应该是判断 enabled 为 True 的情况下才需要执行？

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +            return
如果 enabled 为 False ，应该是 metering 和 notification 这 2 个 loopiingcall 都没有 start 才对？

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +            return
这里和 metering_loop 一样，需要考虑把 enabled 的判断放到 loopingcall 的层面。

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +        self.last_report = ts
last_report 时间戳更新应该在 notifier 完成之后。

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +    def guest_eayun_monitor_update(self, context, configuration=None):
[unused-argument] Unused argument 'context' [python/pylint]

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +        and restart the metering_loop.
注释可以改下了，用 2 个 loopingcall ，可能重启的就不只 metering_loop 了。

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +        config.readfp(open(FILEPATH, "rw"))
[bad-open-mode] "rw" is not a valid mode for open. [python/pylint]

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +                raise exception.BadRequest(_("Invalid configuration item."))
到了 guestagent 这里，已经不能按照 api 的要求对输入进行检查了，而且 guestagent 抛出的异常不会原样到达 api （因为 api 到 guestagent 是通过 rpc ，2 者并不是同一个进程）。基本的合法性检查（格式等）要放到 api 里。

由于 eayunstack_monitor 的配置项是在 trove/cmd/guest.py 里注册的，所以在 api 应该没有办法直接检查配置项是否合法，当然一定要检查的话，可以把配置项的注册放到 trove/common/cfg.py 里去。另一种方案是在 api 里不具体检查配置项是否合法，对于不支持的以及不合法（比如 interval 小于 0 ，enabled 不是 bool 类型）的配置项，在 guest_eayun_monitor_update 这里直接忽略就行了。

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +            config.write(open(FILEPATH, "w"))
这种打开文件的方式不太好，可以把整个读取、更新配置文件的过程做一个 context ：
```
with open(...) as config_file:
   ...
```

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +                initial_delay = self.measure_interval - delta
如果要保证下一次采集和未修改配置之前保持一致的话，initial_delay 应该总是要设置为原 mesure_interval  减去 delta ，不需要判断新的 measure_interval 大于 原 mesure_interval 。

而且这里也可能出现 delta 大于原 measure_interval 的情况，这种情况下， initial_delay 只能设置为 0 。

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +                initial_delay = self.report_interval - delta
这里和上面 metering_loop 一样，不需要判断 report_interval > self.report_interval ，另外要处理 initial_delay 小于的 0 的情况。

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +                                                  initial_delay=initial_delay)
总体来说，更新配置的过程还是有问题。
1. 需要根据配置变化的情况进行处理，如果配置项没有发生变化是不需要重启的，另外，如果把 enabled 改为控制 loopingcall 本身的话，还会有只做 stop 不做 start 的情况（即 enabled 从 True 变为 False ）；
2. metering 和 notification 是 2 个 loopingcall ，应该独立进行重启。比如，可能出现只修改了 metering 的 interval ，这样只需要重启 metering_loop ；

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        # innodb_buffer_pool_size
+1

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +                            'Innodb_buffer_pool_pages_dirty')
[bad-continuation] Wrong hanging indentation (remove 16 spaces). [python/pylint]

下面还有好几处分行导致的缩进格式问题，不一一说明。

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        max_connections = mysql_variables.get('max_connections')
这个文件大部份的数据之都是用 get_item 来获取的，直接用 dict.get() 之后，需要给一个默认值，不然当 dict 里没有指定 key 的时候，会返回 None 。

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/service.py
> +            data_dict = dict(data_list)
dict 转换的问题参见 get_mysql_variables 。

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/service.py
> +            data_dict = dict(data_list)
client.execute 返回的是 ReusltProxy 对象，不能直接用于初始化 dict ，可以用 ResultProxy 的 fetchall 方法得到一个列表或者 __iter__ 方法得到一个 iterator ，然后生成一个 dict 。

2017-10-23 07:34 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/service.py
> +            data_dict = dict(data_list)
dict 转换的问题参见 get_mysql_variables 。

2017-10-23 07:40 UTC, zhaochao commented on trove/instance/service.py
> +        if not body or type(body) != dict:
[unidiomatic-typecheck] Using type() instead of isinstance() for a typecheck. [python/pylint]

2017-10-23 07:48 UTC, jinhui-li commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +        mongoDBAdmin = service.MongoDBAdmin()
这里是因为service文件也会importmeteringapp,如果直接在文件开头import会导致循环导包,服务都起不来,所以就放在了使用的地方import

2017-10-23 07:50 UTC, jinhui-li commented on trove/guestagent/datastore/manager.py
> +            return
那我把这个判断放到启动loopingcall的地方?

2017-10-23 07:55 UTC, jinhui-li commented on trove/guestagent/datastore/manager.py
> +    def guest_eayun_monitor_update(self, context, configuration=None):
当时自测的时候好像不传context会报错

2017-10-23 07:59 UTC, jinhui-li commented on trove/guestagent/datastore/manager.py
> +            config.write(open(FILEPATH, "w"))
当时我也是想这么写,但是好像是因为读写都需要这样写一个,当时各种错,为了简单就按现在这种方式做了

2017-10-23 08:09 UTC, zhaochao commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +        mongoDBAdmin = service.MongoDBAdmin()
这样的话，就不应该在这个文件里 import service 了，可以在初始化 MongoMeteringApp 时直接把 MongoDBAdmin 实例传递进来就可以了。

2017-10-23 08:14 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +    def guest_eayun_monitor_update(self, context, configuration=None):
噢，明白了， rpc call 要用到，那这样不用管了。

2017-10-23 08:59 UTC, jinhui-li commented on trove/guestagent/datastore/manager.py
> +                initial_delay = self.measure_interval - delta
如果 delta 大于原 measure_interval的话,中间肯定已经执行过一次任务,所以应该不会出线这种情况

2017-10-23 09:04 UTC, jinhui-li commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        max_connections = mysql_variables.get('max_connections')
dict 里没有指定 key 的时候,我都指定为了0,其他都是肯定存在的

2017-10-23 09:16 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +                initial_delay = self.measure_interval - delta
不是，delta 大于 measure_interval ，说明采集任务由于什么原因卡住了，导致没有很快完成。

2017-10-23 09:21 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        max_connections = mysql_variables.get('max_connections')
嗯，没有指定默认的 key 确认一定存在就可以。

2017-10-24 01:45 UTC, jinhui-li commented on trove/guestagent/datastore/manager.py
> +                raise exception.BadRequest(_("Invalid configuration item."))
那我就在api层面,对传入的dict做检查,判断那三个字段在不在dict里面,然后继续判断合不合法

2017-10-24 05:46 UTC, zh-f approved these changes

2017-10-24 07:29 UTC, zhaochao requested changes

2017-10-24 07:29 UTC, zhaochao commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +        serverStatus = service.MongoDBAdmin().server_status()
不要 import service 了，直接在初始化 MongoMeteringApp 把 MongoDBAdmin 传进来吧，可以是已经初始化的实例，这样和 RedisMeteringApp 是一样的。也可以直接把 class 传进来，用的时候才实例化，这样就和 MysqlMeteringApp 是一样了。

2017-10-24 07:29 UTC, zhaochao commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +                total += int(serverStatus['opcounters'][db])
这里用 2 个 list 应该也没什必要，可以用一个 dict ，后面同样用 for 循环，比如：
```
op_mappings = {
    'insesrt': 'mongo.insert.requests',
    ...
}
for op, status_op in op_mappings.iteritems():
    ...
```

当然还有另外的作法，本身 dblist 里的元素都是 trovelist 里对应元素的一部份而且格式完全相同，所以只有一个 list 也可以：
```
ops = ['insert', ...]
for op in ops:
    counter[op] = serverStatus['opcounters']['mongo.%s.requests' % op]
    ...
```

2017-10-24 07:29 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +        if self.eayun_monitor_enabled is True:
is True 多余了。

2017-10-24 07:29 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +        for option, value in configuration.items():
用 iteritems() 。

2017-10-24 07:29 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +            if config.get('eayun_monitor', option, True) != value:
elif ？

2017-10-24 07:29 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +            if self.measure_interval != measure_interval:
这个 if 和后面的 if self.report_interval != report_interval: 应该是在一个 else 之下的，即 eayun_monitor_eanbled 为 True 的情况下进行。

2017-10-24 07:29 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +                    initial_delay=initial_delay)
重启 loopingcall 的过程是一样的，可以封装成一个函数来用。

2017-10-24 07:29 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +                   }
[bad-continuation] Wrong continued indentation (remove 1 space). [python/pylint]

2017-10-24 07:44 UTC, jinhui-li commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +                total += int(serverStatus['opcounters'][db])
学到了

2017-10-24 07:47 UTC, jinhui-li commented on trove/guestagent/datastore/manager.py
> +                    initial_delay=initial_delay)
封装成一个函数感觉参数比较多,感觉不如这样看着舒服呢

2017-10-24 08:00 UTC, zhaochao commented on trove/guestagent/datastore/manager.py
> +                    initial_delay=initial_delay)
嗯，后面的 stop() 、重新初始化、和 start() 没办法方便的简化就算了。

不过前面计算 initial_delay 就完全没必要重复写 2 遍，可以抽出来做成一个函数，叫 calc_initial_delay 之类的，直接在 if self.measure_interval != measure_interval: 前面定义这个函数就可以，本身也只在 guest_eayun_monitor_update 里使用。

2017-10-24 08:21 UTC, jinhui-li commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +                   }
flake8 不报这个格式错误

2017-10-24 08:25 UTC, zhaochao commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +                   }
嗯， pylint 会报，在前面去掉一个空格就好了。

2017-10-24 08:28 UTC, zh-f submitted a review, later dismissed
zhaochao看的太细致了……再改改吧

2017-10-24 08:59 UTC, jinhui-li commented
After finishing yours comment, the code looks much better, thx!

2017-10-24 09:15 UTC, merged

2017-10-24 09:43 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +            if float(maxConns) != 0:
这里`maxConns`总是一个整数，为什么要转成`float`再和0比较？

2017-10-24 09:43 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +            # insert,query,update,delete,getmore,command,total
typo，逗号后需要有空格

2017-10-24 09:43 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +            }
这个`dict`看起来key和value的关系是固定的，直接在下面的循环里用`status_op = "mongo.%s.requests" % op`不可以吗？这样子不需要预先定义好一个这样一个临时dict

2017-10-24 09:43 UTC, huntxu commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +                            'mongo.total.requests': total})
如果后面两者表示一个东西，那么应该没什么必要分别作为两个指标存在和报告

2017-10-24 09:43 UTC, huntxu commented on trove/guestagent/datastore/experimental/redis/meteringapp.py
> +                keys += int(info['db' + str(i)]['keys'])
一般相同的内容不会计算两次，应该考虑把`'db' + str(i)`先保存在临时变量里

2017-10-24 09:43 UTC, huntxu commented on trove/guestagent/datastore/manager.py
> +        config.readfp(open(FILEPATH, "r"))
这样子打开的文件描述符会一直存在不关闭直到进程退出，所以不要这么用。

964行 @zhaochao 给了一个好的做法。

2017-10-24 09:43 UTC, huntxu commented on trove/guestagent/datastore/manager.py
> +        for option, value in configuration.iteritems():
`configuration`默认值是`None`，没有`iteritems`的方法

2017-10-24 09:43 UTC, huntxu commented on trove/guestagent/datastore/manager.py
> +                                          True)
`measure_interval`的默认值是`True`，表示多少？下面`report_interval`也一样

2017-10-24 09:43 UTC, huntxu commented on trove/guestagent/datastore/manager.py
> +                    self.metering_loop_task = \
`metering_loop_task`这个应该不需要重新赋值，这里只涉及重新启动和修改间隔时间而已。另一个task一样

2017-10-24 09:43 UTC, huntxu commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        max_connections = mysql_variables.get('max_connections')
如果取出来的内容是字符串，不是最终要报告的类型，那么应该先在获取的时候进行类型转换，避免在一个地方获取，到另一个地方(`counter.update`)的地方做类型转换的行为。

另外值得注意的地方是，如果不能确保`mysql_variables`（或者下面的其他dict）中总有预期成员，那么应该考虑到`dict.get`的默认返回值是`None`，不可以直接用`int()`

2017-10-24 09:43 UTC, huntxu commented on trove/guestagent/datastore/mysql_common/meteringapp.py
> +        connections = mysql_status.get('Connections')
这里不参与计算的数据不少，这才是一个需要用临时的dict来做map的场景。
```
for counter_name, status_name in XXX_map:
    counter[counter_name] = int(mysql_status.get(status_name, 0))
```

当然，`int(mysql_status.get(status_name, 0))`多处可能需要复用，得考虑写成临时函数了

另外需要吐槽这个函数和返回值的命名，明明应该是复数的`get_counters`和`counters`

2017-10-24 09:43 UTC, huntxu commented on trove/instance/service.py
> +                                 measure_interval < 0):
如果要和下面的报错匹配的话，这里的比较符号应该是`<=`

2017-10-24 09:43 UTC, huntxu commented on trove/guestagent/datastore/manager.py
> +    def guest_eayun_monitor_update(self, context, configuration=None):
这个是否对应api部分转过来的调用，api部分的调用没看到传了`context`参数

2017-10-24 09:45 UTC, huntxu commented
我手慢了 :)
最后的评论里面，`context`参数的传递那个以及文件描述符的两个比较重要。

2017-10-24 09:48 UTC, 2hf commented
@huntxu emmmmm...确实手慢了…… 😂

2017-10-24 09:51 UTC, jinhui-li commented on trove/guestagent/datastore/manager.py
> +        for option, value in configuration.iteritems():
在api层面已经做了检查,保证传过来的是dict

2017-10-24 09:52 UTC, huntxu commented on trove/guestagent/datastore/manager.py
> +        for option, value in configuration.iteritems():
如果保证传过来是`dict`，那么这个函数的声明处这个参数就不需要指定默认值，否则会有歧义

2017-10-24 09:54 UTC, jinhui-li commented on trove/guestagent/datastore/experimental/mongodb/meteringapp.py
> +                            'mongo.total.requests': total})
chenyb要求的

2017-10-24 09:55 UTC, jinhui-li commented on trove/guestagent/datastore/manager.py
> +    def guest_eayun_monitor_update(self, context, configuration=None):
rpc要求传的,自测时不传报错

2017-10-24 09:56 UTC, jinhui-li commented on trove/guestagent/datastore/manager.py
> +                                          True)
这个True不是表示的默认值

2017-10-24 10:01 UTC, zhaochao commented on trove/instance/service.py
> +                                 measure_interval < 0):
嗯，这里需要改下。等于 0 应该是会有问题，其实 interval 太小可能也有问题。

2017-10-24 10:10 UTC, huntxu commented on trove/guestagent/datastore/manager.py
> +                                          True)
噢，回去看了下ConfigParser，这里是我弄错了