WIP:MongoDB: enable to create replicate set cluster.
eayunstack/trove pull request #44
Opened 2017-09-21 06:12 UTC by caisan

By default, trove MongoDB can only create type of sharding cluster.
this PR aims to add a type named replic_set, which is a another type of cluster with 3 instance.

2017-09-27 07:20 UTC, 2hf commented
在commit message和PR的内容中还是要标明对应Redmine上的feature的……

2017-10-17 06:30 UTC, zh-f requested changes

2017-10-17 06:30 UTC, zh-f commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +               instances, extended_properties, locality, cluster_type):
在创建集群的方法中，最开始会对实例数目做检查，目前代码中，如果实例数目不是3，就会raise异常，提示集群实例数目不支持。如果产品需求中对集群节点数要求大于3，比如5或者7，那这里可能要考虑下是否需要修改实现。

2017-10-17 06:30 UTC, 2hf commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                instance_name = "%s-%s-%s" % (name, replica_set_name, str(i + 1))
这里的replica_set_name上面指定了值为'rs1'——replica_set_name = "rs1"，那创建的所有的复制集都叫这个名字感觉怪怪的。

2017-10-17 06:30 UTC, 2hf commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +            if query_routers and config_servers:
这行代码上面空一行即可，目前空行太多（空行为2）

2017-10-17 06:30 UTC, 2hf commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
>                                   for instance in config_servers]
continuation line under-indented for visual indent. 换行在 ``[`` 后面比较好吧，跑一下flake8吧，后面还有些问题，比如缺少空格，注释的``#``后面要跟一个空格。

2017-10-17 06:30 UTC, 2hf commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +        #we dont need query_router,
这段注释再斟酌一下，注意格式。

2017-10-18 03:20 UTC, zhaochao commented
看起来 4 个 commit 都是相关的内容，应该合并成一个。

另外合并 commit 之后需要注明对应的 redmine issue ，同时要记得修改 pull request 的说明。

2017-10-18 05:54 UTC, zhaochao requested changes

2017-10-18 05:54 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +        #create replica set mongo cluster
E265 block comment should start with '# ' [python/pep8]

2017-10-18 05:54 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +        elif cluster_type is None:
因为只有 2 种情况，这来应该用 else 就可以。

不过 cluster_type 是用户输出的，所以应该考虑 api 处理请求时是否要进行合法性检查。

2017-10-18 05:54 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                instance_name = "%s-%s-%s" % (name, replica_set_name, str(i + 1))
E501 line too long (80 > 79 characters) [python/pep8]

2017-10-18 05:54 UTC, zhaochao commented on trove/cluster/models.py
> +                                                 locality, cluster_type)
直接增加 1 个 cluster_type 对所有的 cluster strategy 都有影响，不能只在 cluster/model 这里修改。

2017-10-18 05:54 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                                            modules=instances[i].get('modules'))
E501 line too long (80 > 79 characters) [python/pep8]

2017-10-18 05:54 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                instance_name = "%s-%s-%s" % (name, replica_set_name, str(i + 1))
E501 line too long (80 > 79 characters) [python/pep8]

2017-10-18 05:54 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                                            modules=instances[i].get('modules'))
E501 line too long (80 > 79 characters) [python/pep8]

2017-10-18 05:54 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +    def _create_replic_set(self, members):
typo ，习惯上应该是 replica_set 。

2017-10-18 05:54 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +        if not self._init_replica_set(primary_member,other_members):
[bad-whitespace] Exactly one space required after comma [python/pylint]

2017-10-18 05:54 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +        #so we dont need to add replica_set to query_router as a shard
上面 2 行注释：
[trailing-whitespace] Trailing whitespace [python/pylint]
E265 block comment should start with '# ' [python/pep8]

2017-10-18 05:54 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +        if cluster_type == "replica_set":
看 taksmanager 里的 _init_replica_set ，member_config 里的 shard_id 对于 replica set 集群来说没有作用，应该去掉，前面初始化 member_config 时也应该根据 cluster_type 不同分别进行。

2017-10-18 05:54 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +                  % (replica_set, primary_member.shard_id, self.id))
前面提到过了正常情况下对于 replica set 集群的实例来说不应该有 shard_id 这个属性。

2017-10-19 06:58 UTC, zhaochao commented
mongodb cluster 支持的 api 包括：
- create
- show
- delete
- list
- grow（action）
- add_shard （action）

目前对 replica set 的支持，只处理了 create ，简单看了下代码 show 、delete 、list 应该都没有问题。但是 grow 和 add_shard 会有问题，需要进行处理。

2017-10-20 06:47 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +               instances, extended_properties, locality, cluster_type):
@2hf 目前产品要求的集群数量是3/5/7. 嗯,这里是需要检查下实例数量. 在这里添加了对集群数量的检测, 目前只支持实例数量为3/5/7的集群创建.

2017-10-20 07:04 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                instance_name = "%s-%s-%s" % (name, replica_set_name, str(i + 1))
@2hf 这里的```replica_set_name```代表的是集群内部的一个编号. 用户在API中设置了名字的,
那么,最终用户创建的集群中的实例名字是这样的: 名字-rs1-No, 名字-rs2-No, 名字-rs3-No

2017-10-20 07:05 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +            if query_routers and config_servers:
@2hf 嗯,这里需要修改.

2017-10-20 07:08 UTC, caisan commented on trove/cluster/models.py
> +                                                 locality, cluster_type)
@zhaochao 也就是时候,需要在redis/MySQL等所有的cluster strategy中都要添加相关的```cluster_type```这个参数

2017-10-20 07:46 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +        if cluster_type == "replica_set":
@zhaochao 默认的member-config还是保留吧, 我在```cluster_type = replica_set```里面重新使用member-config

2017-10-20 07:51 UTC, zhaochao commented on trove/cluster/models.py
> +                                                 locality, cluster_type)
具体怎么改，你可以再研究下，如果在 cluster/models 这里调用 strategy 的 create 方法里增加一个参数的话，那所有 cluster strategy 的 create 方法肯定都要改的。

2017-10-20 07:57 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +        if cluster_type == "replica_set":
这里是说明，你应该把 cluster_type 的判断提到更早的地方，member-config 也是根据 cluster_type 不同来初始化。

2017-10-20 08:10 UTC, caisan commented
@2hf @zhaochao 
这个是为了方便测试副本集功能写的简单的脚本, 我之前用的:https://gist.github.com/caisan/efd158a059432d5e7618011a2edfbc5d
有什么不完善的地方,请指正,或者修改下,谢谢 :)

2017-10-20 08:11 UTC, caisan commented
https://gist.github.com/caisan/efd158a059432d5e7618011a2edfbc5d
这个脚本简单的测试了**_创建_**副本集这个功能点. @2hf @zhaochao

2017-10-20 08:13 UTC, caisan commented
@zhaochao grow在需求中还没有明确要求,暂时就没有去管. add_shard不属于副本集范畴的,所以也不予考虑.

2017-10-20 08:14 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +        elif cluster_type is None:
嗯, 这里应该检查.

2017-10-20 08:23 UTC, zhaochao commented
@caisan 需求没有，但是代码里得处理，目前如果对 replica set 集群发起了 grow 和 add_shard 是会发生异常报错的，这里说的处理是把 api 响应处理好，给出正确的错误响应就可以了。

2017-10-20 10:01 UTC, caisan reviewed
@zhaochao 这样啊,嗯,明白了

2017-10-20 10:01 UTC, caisan commented on trove/cluster/models.py
> +                                                 locality, cluster_type)
@zhaochao 实际上cluster type保存在request body中的, 但是在```cluster/service.py```中就已经处理了body了. 我想也就只有该成目前的create方法这样子了.在create中增加参数.

2017-10-24 02:58 UTC, zhaochao requested changes

2017-10-24 02:58 UTC, zhaochao commented on trove/cluster/service.py
> +                raise exception.BadRequest(message=cluster_type)
cluster_type 的检查要放到 mongodb cluster strategy 的 api 里去，trove/cluster/service.py 是对所有 datastore 通用的检查。对于其它 datastore 的 cluster 来说，不一定支持 replica_set 这种类型的 cluster 。

2017-10-24 02:58 UTC, zhaochao commented on trove/cluster/models.py
> +                                                 locality, cluster_type)
我看了一下，所有 cluster strategy 的 create api 都加上 cluster_type 参数感觉不太好。

这里可以利用一下 api_strategy 。api_strategy 对应是 cluster strategy api 类，对于 mongodb 来说就是 MongoDbAPIStrategy ，可以给这个类加一个属性，比如 support_cluster_type ，然后可以根据类是否包含这个属性（以及这个属性是否 True ）来调用 api_strategy.cluster_class.create 方法（支持 support_cluster_type 时，create 方法增加 cluster_type 参数）。

这样就只需要改动 trove/common/strategies/cluster/experimental/mongodb/api.py ，而不需要动其它 datastore 的代码。

2017-10-24 02:58 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/cassandra/api.py
> +               instances, extended_properties, locality, cluster_type):
参见  trove/cluster/models.py 里相关位置新的 comment 。

2017-10-24 02:58 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/galera_common/api.py
> +               instances, extended_properties, locality, cluster_type):
参见  trove/cluster/models.py 里相关位置新的 comment 。

2017-10-24 02:58 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
>              raise exception.ClusterNumInstancesNotSupported(num_instances=3)
如果有效的节点数是一个列表的话，那么后面这个 ClusterNumInstanceNotSupported 需要相应的修改，改动不大，只要保证 exception message 是对得上的就可以。

2017-10-24 02:58 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                                            )
[bad-continuation] Wrong continued indentation (remove 1 space). [python/pylint]

2017-10-24 02:58 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +        elif cluster_type is None:
else 就可以？

2017-10-24 02:58 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                                            )
[bad-continuation] Wrong continued indentation (remove 1 space). [python/pylint]

2017-10-24 02:58 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/vertica/api.py
> +               instances, extended_properties, locality, cluster_type):
参见 trove/cluster/models.py 里相关位置新的 comment 。

2017-10-24 02:58 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/redis/api.py
> +               instances, extended_properties, locality, cluster_type):
参见 trove/cluster/models.py 里相关位置新的 comment 。

2017-10-24 02:58 UTC, zhaochao commented on trove/cluster/service.py
> +            if cluster_type != "replic_set":
typo . replica_set ？

2017-10-24 02:58 UTC, zhaochao commented on trove/cluster/service.py
> +            raise exception.BadRequest(message=msg)
和 cluster_type 一样要放到 mongodb cluster strategy 的 api 里去。

另外 cluster_type 应该明确是 replica_set ，才不支持。

在 mongodb cluster strategy 的 api 里 grow 和 shrink 分别有对应的方法，分开处理也可以。

2017-10-24 03:02 UTC, zhaochao commented
另外 2 个问题：
1. commit message 里和别的 commit 要持持一致。 对应的 redmine issue 要写成：
```
Fixes: http://192.168.15.2/issues/xxxx
```

2. 更新 pull request 的时候，不能总是提交新的 commit ，对应这个 pull request ，新的改动都应该合并成一个 commit ，目前看没有分成多个 commit 的必要。

2017-10-25 02:36 UTC, zhaochao requested changes

2017-10-25 02:36 UTC, zhaochao commented on trove/cluster/models.py
> +            if api_strategy.supported_cluster_type:
2 个 if 合成一个吧。

另外，类属性命名不太好， support_cluster_type ，supported 不太对

2017-10-25 02:36 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +            raise exception.ClusterNumInstancesNotSupported(num_instances="3 or 5 or 7")
E501 line too long (88 > 79 characters) [python/pep8]

2017-10-25 02:36 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                                            modules=instances[i].get('modules'))
这里还是太长了。

2017-10-25 02:36 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                                            modules=instances[i].get('modules'))
这里也没改。

2017-10-25 02:36 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +            raise exception.BadRequest(message=msg)
调用 action 时应该没有传递 cluster_type 参数，这里应该还是用 query_routers 作辅助判断。

2017-10-25 09:40 UTC, zhaochao requested changes

2017-10-25 09:40 UTC, zhaochao commented on trove/cluster/models.py
> +                                                         locality, cluster_type)
上面几行有缩进、行长度的问题。跑下 pep8 和 pylint 。

2017-10-25 09:40 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +            if cluster_type != "replica_set":
上面 2 个 if 也合并到一起吧。

2017-10-25 09:40 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                                                        type=type_i).all()
这里看起不用额外调一次数据库接口，参考 _prep_resize 里 _instances_of_type 的实现的。

2017-10-25 10:04 UTC, zhaochao approved these changes

2017-10-25 10:05 UTC, merged