Backup: backup instances within cluster
eayunstack/trove pull request #56
Opened 2017-11-09 07:26 UTC by caisan

This PR aims to support for backing up the instances, which
is a part of a cluster. before this commit, try to backup a instance
which belongs to a cluster will raise exception:ClusterInstanceOperationNotSupported

Fixes:

2017-11-09 08:12 UTC, huntxu requested changes

2017-11-09 08:12 UTC, huntxu commented on trove/backup/models.py
> +            #    raise exception.ClusterInstanceOperationNotSupported()
Dead codes are not meaningful comments.

2017-11-21 02:41 UTC, zhaochao requested changes

2017-11-21 02:41 UTC, zhaochao commented on trove/backup/models.py
> -                raise exception.ClusterInstanceOperationNotSupported()
应该仔细研究一下，原来代码增加这两行的原因。

对于 cluster 来说，可能存在某些实例不能进行备份的情况，因此这里需要进行更多的检测，不能简单全部允许。

2017-11-27 07:01 UTC, caisan commented on trove/backup/models.py
> -                raise exception.ClusterInstanceOperationNotSupported()
@zhaochao Trove之所以在这里不允许对mongoDB集群备份,是因为原生使用的是sharding集群, sharding集群备份时配置服务器和分片上的数据是单独备份的,可能会造成数据不一致的情况,因此Trove这里就直接不支持了. 但是我们用到的是副本集, 这里就去掉了.

2017-11-27 07:09 UTC, zhaochao commented on trove/backup/models.py
> -                raise exception.ClusterInstanceOperationNotSupported()
代码肯定不能直接这样改，虽然别的代码我们目前用不上，但是不能假定以后不会用到，直接这样修改，会影响原来代码的行为。

比较直接简单的方案是，从 cluster_id 拿到 cluster 对象，在 cluster 对象里增加判断能否进行备份的方法，默认情况下不允许备份，我们用到 replica set 集群允许备份。

2017-11-27 09:19 UTC, zhaochao commented on trove/backup/models.py
> +from trove.cluster import models
这里直接  from trove.cluster.models import Cluster as DBCluster 吧，models 容易混淆。

2017-11-27 09:19 UTC, zhaochao commented on trove/backup/models.py
> +                        not cluster.allow_backup():
cluster 可能有多个 instsance ，这里 allow_backup(instance_id) 应该更合理一些。

2017-11-27 09:19 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                       if db_inst.type == type_q or db_inst.type == type_c]
可以这样：
non_member_types = ['query_router', 'config_server']
...
               if db_inst.type in non_member_types ]
..

2017-11-27 09:43 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                       if db_inst.type == type_q or db_inst.type == type_c]
噢，看了下上次的  action 方法，应该只需要判断有没有 query_router 就可以了。

另外，增加了 replica set 集群以后，有很多地方会判断集群类型，可以考虑单独实现一个方法或者是实例属性来做这件事。

2017-11-27 10:51 UTC, caisan commented on trove/backup/models.py
> +                        not cluster.allow_backup():
@zhaochao 备份的不是cluster-id, 是instance_id, 因此这里就确定了是哪个instance.只是看这个instance所属的cluster对象能不能备份就可以了.

2017-11-27 11:02 UTC, zhaochao commented on trove/backup/models.py
> +                        not cluster.allow_backup():
暂时这样也可以，其实我的意思是，cluster 里可能出现某些 instance 能够进行备份，某些不能，这样就需要通过 instance_id 来判断了，不过目前我们没有这样的情况。

2017-11-27 11:12 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +        if len(is_sharding):
is_sharding 命名不太好。另外，之前说过，相似的代码在这个文件里已经出现至少 2 次了（上次还有 action ），可以考虑增加一个方法或者属性来完成这个操作。

2017-11-27 12:52 UTC, zhaochao requested changes

2017-11-27 12:52 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +    def get_type(self, db_instances):
db_instances 没用到。

2017-11-27 12:52 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +        if len(query_routers):
`if len(query_routers) > 0:` 吧，这样比较清楚。

2017-11-27 12:52 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +    def get_type(self, db_instances):
可以加上 `@property` 修饰器。这样的话，可以直接使用，而不是以函数调用的方式，比如：
```
@property
def type(self):
    ...

def action(...):
    ...
    if self.type == "replica-set":
...
```

2017-11-27 12:52 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +        return True
直接 return ？

（这里改成用 property ）
```
...
    return self.type == "replica-set"
...
```

2017-11-28 02:24 UTC, huntxu requested changes

2017-11-28 02:24 UTC, huntxu commented on trove/backup/models.py
> +                    raise exception.ClusterInstanceOperationNotSupported()
我看实例的创建，这里的判断看起来不需要这么复杂。其实这里只想在上面`instance_model.cluster_id is not None`的情况下过滤掉允许备份的mongo的replica-set类型的集群，这些内容只通过instance_model应该能够解决才是。判断实例是一个mongo应该可以用`instance_model.datastore`，判断集群是replica-set应该可以用`instance_model.shard_id == None`。

当然为以后mongo的集群可能增加更多考虑的话，这里添加`allow_backup`的属性没什么问题。但问题是backup是对实例而言，因此`allow_backup`也应该作为实例的属性存在，而不是在集群中判断。验证应该扩展`Backup.validate_can_perform_action`去读取实例的该属性。该属性的初始化应该在实例创建时根据不同的datastore和集群类型进行，或者作为`@property`属性在获取时根据datastore和cluster_id和shard_id返回。

2017-11-28 02:57 UTC, zhaochao commented on trove/backup/models.py
> +                    raise exception.ClusterInstanceOperationNotSupported()
这样本意是要对不同数据库服务的 cluster 进行支持，也就是说数据库服务的 cluster 中可能会有不同角色的 instance ，只有 cluster 才能确定某一个 instance 是否能进行备份， shard_id 并不能完全决定，所以原来希望 allow_backup 要加上一个 instance 参数来进行判断，不过对于 mongodb 来说暂时没有这么复杂，没有加上这个参数，导致 allow_backup 也变得像是 cluster 的一个属性。

2017-11-28 03:15 UTC, huntxu commented on trove/backup/models.py
> +                    raise exception.ClusterInstanceOperationNotSupported()
make sense，这样子考虑是比bug里的需求和我前面的预想仔细些。看前面的讨论就只是以为这里要去除对mongo replica-set的实例的限制，commit message里也不是很清楚。

另外建议cluster里的`allow_backup`附近加上些注释说明，因为那里用了`@property`所以误解了。

2017-11-28 03:16 UTC, caisan commented on trove/backup/models.py
> +                    raise exception.ClusterInstanceOperationNotSupported()
@huntxu 实际上不是备份一个mongo的replica-set类型集群. 备份的是集群中的实例. 而且只允许replica-set集群中的实例备份.```allow_backup```因此作为mongoDB cluster的一个属性.

2017-11-28 03:38 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +        """
同意 @huntxu 的意见，我们可以在这里加上一些说明，说明对于不同的 cluster ，可能存在某些集群实例可以备份，另一些不能备份的情况，对于 MongoDB 来说，暂时只是 replica set 允许对任一集群实例进行备份，sharded 集群则任何实例都不能进行备份，因为 allow_backup 有所简化。

2017-11-28 03:48 UTC, huntxu commented on trove/backup/models.py
> +                    raise exception.ClusterInstanceOperationNotSupported()
@caisan 上面的讨论应该比较清楚，`allow_backup`并非集群的属性，而是集群的一个方法。 @zhaochao 的评论中的思路扩展了原来只考虑允许mongo replica-set集群中实例备份的简单逻辑，将这种简单的判断推广到了更底层由集群来对一个实例是否能够备份进行判断。

2017-11-28 05:23 UTC, caisan commented on trove/backup/models.py
> +                    raise exception.ClusterInstanceOperationNotSupported()
@huntxu 嗯, 明白. 也就是说不是简单的由集群类型来判断是否可以备份, 还进一步判断了集群中哪些实例可以备份, (只不过这一步对于mongoDB来说现阶段就省略了)

2017-11-28 05:51 UTC, zhaochao commented on trove/backup/models.py
> +                        not cluster.allow_backup():
调用 allow_backup 时，要加一些注释进行说明，参见 trove/common/strategies/cluster/experimental/mongodb/api.py 里 allow_backup 定义那里被删去的 comment 。

2017-11-28 08:43 UTC, zhaochao approved these changes

2017-11-28 08:43 UTC, merged