Add Trove Pass Database Monitoring Features 2th
eayunstack/trove pull request #57
Opened 2017-11-10 08:28 UTC by jinhui-li

2017-11-10 08:35 UTC, zh-f approved these changes
LGTM 👍

2017-11-10 08:48 UTC, zhaochao commented
commit message 需要修改：

第一行，不好总结的话，可以写类似“monior fixes for Trove database monitoring” 。

后面一段可以说明是针对 #40 （60998d94271f8ec633241b6b274187cd3fc14ae1）的修复。

2017-11-10 08:48 UTC, zhaochao requested changes
commit message 需要修改：

第一行，不好总结的话，可以写类似“monior fixes for Trove database monitoring” 。

后面一段可以说明是针对 #40 （60998d94271f8ec633241b6b274187cd3fc14ae1）的修复。

2017-11-10 09:25 UTC, zhaochao requested changes
改动应该没什么问题，可以合并。

不过 commit message 还是不太好。第一行之后的正文需要写的更清楚一些，比如：
1. 大致有哪些改动（各项改动可简单说明一下）；
2. 是针对 #40 （这个写成 `github pull request #40` 比较好) 中 huntxu 的评论的修改；

2017-11-13 03:29 UTC, zhaochao approved these changes

2017-11-13 03:29 UTC, merged