Replica Set: os_mongo_admin_creds for all nodes
eayunstack/trove pull request #60
Opened 2017-11-23 03:29 UTC by caisan

By default, os_mongo_admin_creds.json only store on the primary,
but when primary change to other member node, cannot execute operation with
admin user, this commit create os_mongo_admin_creds.json for all node.
With os_mongo_admin_creds.json on all node, any operation needs admin user can be executed.

2017-11-23 05:37 UTC, zhaochao requested changes
代码逻辑感觉没错，但是有几个问题：
1、commit msg ，第一行（title line）写得不好，应该明确是 mongodb ，所以大概应该是类似 “Saving admin_creds on all MongoDB Replica nodes” ；

2、单独一个 pull request 的话，应该加上一个对应的 Redmine Issue ；

3、prep_primary 用到的地方很明确，所以可以直接修改，也不会影响原有的行为，应该没有必要增加一个 prep_primary2 。

2017-11-23 07:31 UTC, caisan commented
@zhaochao ```prep_primary2()```是因为这里要传入一个password, 而在sharding集群中不需要传入password, 所以就新增加了一个```prep_primary2 ()```表示区分.

2017-11-23 07:45 UTC, huntxu commented
> prep_primary2()是因为这里要传入一个password, 而在sharding集群中不需要传入password, 所以就新增加了一个prep_primary2 ()表示区分.

可以在`prep_primary()`里增加多一个参数`password=None`之类来解决这种问题。

另外`_init_replica_set`只用了一次，看不到不能直接改动而要新增一个`_init_replica_set2`的原因

2017-11-23 07:51 UTC, zhaochao commented
> prep_primary2()是因为这里要传入一个password, 而在sharding集群中不需要传入password, 所以就新增加了一个prep_primary2 ()表示区分.

如果需要的话，上面 @huntxu 说的就是解决方案。

不过 sharded cluster 和 replica set 在这一步其实是没有区别的，都可以在 api 这里生成 password 再传递到 guestagent 那里进行 replica set 的初始化。

2017-11-27 06:38 UTC, caisan commented
@huntxu @zhaochao 在```_init_replica_set2```中会将```os_mongo_admin_creds.json```保存到secondary节点,而```_init_replica_set```用于sharding集群,则没有这个操作.

2017-11-27 06:45 UTC, zhaochao commented
对于 sharded 集群是一样的，如果 primary 切换，也会出现找不到 credential 文件的情况。

2017-11-27 08:18 UTC, zh-f requested changes

2017-11-27 08:18 UTC, zh-f commented on trove/common/strategies/cluster/experimental/mongodb/guestagent.py
> +    def prep_primary2(self, password):
我暂时没功能性上来考虑，但是这里的命名确实不过关……包括下面_init_replica_set2

2017-11-27 09:10 UTC, caisan commented
嗯, 那就一并把sharding集群的```_init_replica_set```改了.

2017-11-27 11:45 UTC, zhaochao reviewed
除了 mongodb manager 里 prep_primary 的定义（见 inline comment ），看起来没有别的问题了。

2017-11-27 11:45 UTC, zhaochao commented on trove/guestagent/datastore/experimental/mongodb/manager.py
> +    def prep_primary(self, context, password=None):
这里因为没有别的地方会以 prep_primary() 这种方法调用，所以不需要为 password 设置 None 为默认值。

2017-11-28 03:38 UTC, zh-f commented on trove/guestagent/datastore/experimental/mongodb/manager.py
> +    def prep_primary(self, context, password=None):
对，password不必做成关键字参数，标准调用即可。

2017-11-28 08:47 UTC, zhaochao approved these changes

2017-11-28 08:48 UTC, merged