MongoDB: restore a seplica set from MongoDB backups
eayunstack/trove pull request #64
Opened 2017-11-27 06:44 UTC by caisan

This pr outlines the process for taking MongoDB data
and restoring that data into a new replica set. Restoring the backup data into a single MongoDB,
then init a replica set, finally add other members into the replica set.

Fix : http://192.168.15.2/issues/11203

2017-11-27 07:55 UTC, zhaochao requested changes

2017-11-27 07:55 UTC, zhaochao commented on trove/cluster/service.py
> +        backup_id = utils.get_id_from_href(backupRef)
需要明确的是，API 中 backup 参数具体的形式。按照这里的写法，参数命名是 backupRef ，从 instances 里获取。 

有几个问题：
1、参数命名，直接用 backup 也没什么问题；
2、在 trove/common/apischema.py 里 cluster create 中 instances 的类型是 array ，应该没有办法增加一个单独的属性，因此，直接放到 cluster 之下作为一个属性即可。
3、这里作为单独一个 api ，支持 backup 作为输入的话，最好对 backup 也进行检查，而不是等到创建实例时。因为等到创建实例再出现异常，会得到一个 error 状态的 cluster 和 instance ，后续清理的工作变多。一开始就进行检查的话，则 cluster 也没有开始创建。

2017-11-27 07:55 UTC, zhaochao commented on trove/cluster/models.py
> +                                                     locality, cluster_type, backup_id=backup_id)
这个如果是设计在支持 support_cluster_type 的情况下，才支持基于 backup 创建集群也可以，前面的 docstring 应该更新一下说明，或者增加单独的注释。

另外：
E501 line too long (97 > 79 characters) [python/pep8]

2017-11-27 07:55 UTC, zhaochao commented on trove/cluster/models.py
> +               instances, extended_properties, locality, cluster_type, backup_id):
E501 line too long (82 > 79 characters) [python/pep8]

2017-11-27 07:55 UTC, zhaochao commented on trove/cluster/service.py
> +                                            locality, cluster_type, backup_id=backup_id)
E501 line too long (88 > 79 characters) [python/pep8]

2017-11-27 07:55 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +               instances, extended_properties, locality, cluster_type, backup_id):
E501 line too long (82 > 79 characters) [python/pep8]

2017-11-27 07:55 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                                            availability_zone=azs[i],
i ？

2017-11-27 07:55 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                primary_config["instance_type"] = "primary"
这里之前讨论过应该从 guestagent 那边取 replica set 角色状态。对于创建来说也没有必要用 instance_type 来区分，默认总是用第一个节点也没问题。

member 这种 instance_type 是不应该随便改动，原因有 2 个：
1、guestagent 一些基本操作依赖于 instance_type ，改成 primary/secondary 会导致部份操作不能完成；
2、primary/secondary 是 MongoDB replica set 的内部状态，如果直接出现在 Trove 的数据库，必然需要另外的逻辑使之与 MongoDB replica set 实际的状态保持同步。

2017-11-27 07:55 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +            """No backup id"""
如果用这种方式的话，这里需要一个 else 。

但是实际上代码重复得太多，需要合并，由于只有第一个实例需要基于 backup 创建，这样的话可以很方便的再在 for 循环里处理，而不需要单独为有 backup_id 这种情况单独进行判断，比如进入 for 循环之前设置 backup_id （如果提供了 backup_id 的话）基本 backup 创建第一个实例成功之后把， backup_id 设置为 None 。

2017-11-27 07:55 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +                members = primary_node + secondary_nodes
见上面的 comments 。

2017-11-27 07:55 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +        return True
这个应该是另一个 pull request 里的改动，不用引入。

2017-11-27 07:55 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +        """check which member with backup id, select it as primary node"""
？

2017-11-27 09:21 UTC, zhaochao commented
另外， commit message 第一行里面，第 2 个 MongoDB 多余了，MongoDB: restore a seplica set from backups 就可以了。

2017-11-27 12:34 UTC, zhaochao requested changes
除了这些，还有之前讨论的在 api 增加 backup 合法性检查的问题。

2017-11-27 12:34 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                                                modules=modules_i)
我之前的评论是说上面这三段代码完全可以合并成一段，比如：
```
...
for i in range(0, num_instances):
    instance_name = ...
    modules_i = ...
    instance = inst_models.Instance.create(...
        ..., backup_id,
        ...)
     if i = 0:
         primary_inst_id = instance.id
         if backup_id is not None:
             backup_id = None
...
```

2017-11-27 12:34 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +            db_info.id, primary_id)
这样的话，一开始就要给 primary_id 一个初始值，比如 None ，不然 primary_id 可能没有定义。

命名也是个问题，primary_member_instance_id ？

2017-11-27 12:34 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +    def create_cluster(self, context, cluster_id, primary_id=None):
primary_id 总是被传进来的话，不需要默认值。

2017-11-27 12:34 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +    def _create_replica_set(self, members, primary_id=None):
同 create_cluster , primary_id 总是被传入的情况下，不应该设置默认值。

2017-11-27 12:34 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +        if primary_id:
if primary_id is not None:

2017-11-27 12:34 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +            if backup_id:
None 值还是用， is None 或者  is not None 来判断。

2017-11-27 12:34 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +            if primary_id in members:
这个判断多余了。

2017-11-27 12:34 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +            other_members = members[1:]
members 是 Instance 对象的列表，但是 primary_id 只是 primary instance 的 id ，pirmary_id 其实不是 members 的一个元素，因此当 primary_id 不为 None ，需要比较 member 的 id 和 primary_id 来找到 primary instance 。

2017-11-27 14:40 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +    def _create_replica_set(self, members, primary_id=None):
@zhaochao 不使用backup-id创建副本集的时候，也要传入primary_id？

2017-11-27 14:42 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +    def _create_replica_set(self, members, primary_id=None):
@zhaochao 嗯，这样也好，默认就是用第一个作为primary。

2017-11-27 14:46 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +            other_members = members[1:]
@zhaochao 既然这样，那就将primary_instance传过来吧，不用primary_instance_id。

2017-11-27 14:50 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +    def create_cluster(self, context, cluster_id, primary_id=None):
Done

2017-11-27 14:58 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +            other_members = members[1:]
members 是在 _create_cluster 里生成的，传递参数时肯定还是 id 方便。

2017-11-27 15:01 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +    def create_cluster(self, context, cluster_id, primary_id=None):
噢，失误了，这里是 rpc 调用，要加参数还得改 taskmanage/api ，可能需要再研究这个方案是否妥当。

2017-11-27 15:01 UTC, caisan commented
@zhaochao API检查部分，添加了：
```
backup_info = Backup.get_by_id(context, backup_id)
if not backup_info.is_done_successfuly.....
if not backup_info.check_swift_object_exist()....
```

2017-11-27 15:22 UTC, zhaochao requested changes

2017-11-27 15:22 UTC, zhaochao commented on trove/cluster/service.py
> +        backup_info = Backup.get_by_id(context, backup_id)
后面这一段，有一个前提：
`if backup_id is not None:`

2017-11-27 15:22 UTC, zhaochao commented on trove/cluster/service.py
> +                if backup_info.size > volume_size:
这里也一样，前提是 backup_id is not None 。

2017-11-27 15:22 UTC, zhaochao commented on trove/cluster/service.py
> +        backup_info = Backup.get_by_id(context, backup_id)
另外，之前讨论过这一部份和 instance/models 里重复了，应该考虑单独实际一个方法，在 instance 和 cluster 都可以调用，另外当 cluster create 已经检查了之后， instance create 那里就不用再检查一遍了。

2017-11-27 15:22 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> -
？
这里和下面有几处只删掉了一行空行，无关改动。

2017-11-27 15:22 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                        primary_inst = instance
上面这个 if ... else 还是可以合并，再看一下我之前的 comment 吧。

2017-11-27 15:22 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                            size and member['volume_size'] != size)):
无关改动。

2017-11-27 15:22 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +            db_info.id, primary_inst)
这里是我之前失误了，这里并不是直接调用 taskmanage 代码，而是通过 rpc 。这样的话，还需要修改 taskmanage/api ，但是就涉及到所有支持 cluster 的 datastore 里 create_cluster 的修改，这样就显得不合适了。

如果不能直接传递 primary_inst 的话，还是只能在 taskmanage 的 create_cluster 内部想办法了。

2017-11-27 15:32 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                            size and member['volume_size'] != size)):
我用pycharm整理了一次格式，是pycharm造成无关改动的吧。

2017-11-27 15:35 UTC, zhaochao commented
另外， commit message 也改错了， replica set 写成 seplica set 了。

发现一个新问题，mongodb guestagent 的 do_prepare 里只有在没有 cluster_config 时才会基于 backup 恢复数据，也就是说目前即使在 api 这端基于 backup 创建了 primary 实例，但是实际上这个 primary 还是没有从 backup 恢复数据。

2017-11-27 15:37 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                            size and member['volume_size'] != size)):
有可能，但是无关改动还是要还原回去的。

2017-11-27 15:48 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +            db_info.id, primary_inst)
看来之前改 cluster api 时还是没有仔细看， taskmanger api 也可以被各个 datastore 的 strategy 重写，也就是说这里如果要改 mongodb 的 create_cluster 方法，可以直接去 mongodb strategy taskmanage 里为 MongoDbTaskManagerAPI 增加新的 create_cluster 就行。

2017-11-27 23:39 UTC, caisan reviewed
@zhaochao 嗯， 在```do_prepare```最后一步才执行的restore, 在这里不判断```cluster_config```也关系也不是很大吧？

2017-11-27 23:39 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +            db_info.id, primary_inst)
嗯，这里我也忽略了，没考虑到使用了rpc ```_call()```。修改所有的datastore倒也还可行，如果不这样的话，还有一种办法：所有的instance都带上backup-id创建。

2017-11-27 23:39 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                        primary_inst = instance
这个能合并？if下面是恢复副本集，else是创建副本集。

2017-11-27 23:39 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                            size and member['volume_size'] != size)):
嗯

2017-11-27 23:39 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +            db_info.id, primary_inst)
在```trove/common/strategies/cluster/experimental/mongodb/taskmanager.py```的```class MongoDbTaskManagerAPI(task_api.API):```类中重写```create_cluster```方法就可以了。

2017-11-28 01:30 UTC, huntxu requested changes

2017-11-28 01:30 UTC, huntxu commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                        primary_inst = instance
这两部分都是创建新实例，代码逻辑几乎完全相同，只有实例名（看下一段）和是否传递backup_id的区别；甚至如果你这里代码没写错的话，唯一的区别是所谓恢复副本集时第一台节点传递了非None的backup_id；因此没看出不能合并的理由。

另外两部分instance_name的生成略有不同，前者会生成X-X-[0123...]，后者是X-X-[1234...]，原因是什么？

2017-11-28 01:30 UTC, huntxu commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +    def _create_replica_set(self, members, primary_inst):
不明白为什么上面是`primary_instance`，到这里又少了几个字母是`primary_inst`，保持一致很困难吗？

2017-11-28 02:47 UTC, zhaochao requested changes

2017-11-28 02:47 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +            members.remove(primary_instance)
之前说过 inst_models.Instance.create 返回的对象和 members 包含的 primary instance 不是同一种对象（前者是 SimpleInstance 对象，后者是 Instance 对象），没法直接操作，所以 rpc 调用时，还是只传递 primary instance id 才行。

2017-11-28 02:47 UTC, zhaochao commented on trove/guestagent/datastore/experimental/mongodb/manager.py
> +        if backup_info:
这里只要判断 cluster_onfig 里没有 shard_id 就可以了，也就是只排除 sharded cluster 的情况。

2017-11-28 03:31 UTC, zhaochao requested changes

2017-11-28 03:31 UTC, zhaochao commented on trove/cluster/models.py
> +                                                     backup_id=backup_id)
参数数量和顺序完全一致的话，不需要加上 `backup_id=` ？

2017-11-28 03:31 UTC, zhaochao commented on trove/cluster/service.py
> +                                            backup_id=backup_id)
这里也是， `backup_id=` 应该没有必要。

2017-11-28 03:31 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> -
无关改动。

2017-11-28 03:31 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> -
无关改动。

2017-11-28 03:31 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                    if i == 0:
这一段需要一些基本的注释来说明一下。

2017-11-28 03:31 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +            db_info.id, primary_inst.id)
这里 primary_inst 可能为空，所以其实前面的 primary_inst 这个变量是没有必要的，直接用 primary_inst_id ，初始值是 None，后面基于备份创建成功之后，才给 primary_inst_id 赋值。

2017-11-28 03:31 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> -
无关改动。

2017-11-28 03:31 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/taskmanager.py
> +            other_members = members
这里本来就是遍历列表，可以一次性把 primary_member 和 other_members 取出来：
```
if primary_inst_id is not None:
    for member in members:
        other_members = []
        if member.id = primary_inst_id:
            primary_member = member
        else:
            other_members.append(member)
```

2017-11-28 03:31 UTC, zhaochao commented on trove/guestagent/datastore/experimental/mongodb/manager.py
> +        if not cluster_config.shard_id and backup_info:
对于 replica set 集群来说， cluster_config 里没有 shard_id 这个 key ，应该用 not in 来判断。

2017-11-28 03:31 UTC, zhaochao commented on trove/cluster/service.py
> +                            backup_size=backup_info.size, disk_size=volume_size)
之前说过了，上面的这些检查在 instance models 那里也有，需要针对创建 cluster 的 instance 这种情况，跳过这部份检查，不然这部份代码就会在创建集群和创建集群的 primary 实例时执行 2 遍。

另外应该新写一个公共的方法（cluster 和 instance 都可以使用），这样可以避免代码重复。

2017-11-28 05:59 UTC, zhaochao commented on trove/guestagent/datastore/experimental/mongodb/manager.py
> +        if not cluster_config.shard_id and backup_info:
这里判断 cluster_config 时还要注意，对于普通 MongoDB 实例， cluster_config 是 None 。

2017-11-28 08:41 UTC, zhaochao requested changes

2017-11-28 08:41 UTC, zhaochao commented on trove/backup/models.py
> +    def validate_backup_info(self, context, datastore, backup_id, target_size):
这里有 2 个问题：
1、目前都是用于 restore 实例，函数名可以更明确一些，比较 validate_for_restore ，名字中的 backup 就没什么必要了，本身是 Backup 类方法。

2、classmethod 是类方法，第一个应该是 cls 。后面用到方法也只能是类方法，实例方法是不使用的，因为没有实例初始化，同时也要把 self 替换成 cls 。

2017-11-28 08:41 UTC, zhaochao commented on trove/backup/models.py
> +            and backup_info.datastore.name != datastore.name):
[bad-continuation] Wrong continued indentation before block (add 4 spaces). [python/pylint]

2017-11-28 08:41 UTC, zhaochao commented on trove/cluster/service.py
> +                    Backup.validate_backup_info(context, datastore, backup_id, volume_size)
这里是每一个 instance 单独进行检查，没有必要，而且 volume 是在一个 if 之内，也就是说可能没有创建集群时，可以不为 instance 指定 volume 配置。

这里需要变通一下， backup validate 还是要提前，然后在 cluster create 这里，可以把所有 instances 的 volume size 都取出来（注意 volume 可能为空）作为一个列表，然后找到最小值，把这个作为 target_size 来检查。（如果所有 instance 都没有指定 volume ， target_size 只能为 None ，这样的话， Backup validate 那里也要修改一下，即只有 target_size 不为 None 时，才需要检查 size ）。

另外按照上述方法改动之后，记得加上注释，说明这样做的原因：目前对于支持从 backup 创建的 cluster （ MongoDB Replica Set ）来说，要求所有实例的数据盘的大小都大于 backup size 。

2017-11-28 08:41 UTC, zhaochao commented on trove/cluster/service.py
> +
E303 too many blank lines (2) [python/pep8]

2017-11-28 08:41 UTC, zhaochao commented on trove/cluster/service.py
> +                    Backup.validate_backup_info(context, datastore, backup_id, volume_size)
另外，
E501 line too long (91 > 79 characters) [python/pep8]

不过这里最后应该会去掉。

2017-11-28 08:41 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                                                           modules=modules_i)
这上面 L154 、L156 、L159 、 L160 、 L162 、L163 都大于 79 个字符了。

2017-11-28 08:41 UTC, zhaochao commented on trove/guestagent/datastore/experimental/mongodb/manager.py
> +        if (cluster_config is None or 'shard_id' not in cluster_config) and backup_info:
E501 line too long (88 > 79 characters)

2017-11-28 08:41 UTC, zhaochao commented on trove/instance/models.py
> +                Backup.validate_backup_info(context, datastore, backup_id, target_size)
E501 line too long (87 > 79 characters) [python/pep8]

2017-11-28 08:41 UTC, zhaochao commented on trove/instance/models.py
> +            if cluster_config is None:
这个可以和上面的 if 合并：
```
if backup_id and cluster_config is None:
```

2017-11-28 08:41 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                        Firstly created instance as primary node,
[trailing-whitespace] Trailing whitespace [python/pylint]

2017-11-28 10:03 UTC, zhaochao requested changes

2017-11-28 10:03 UTC, zhaochao commented on trove/backup/models.py
> +            if backup_info.size > target_size:
这 2 个 if 也合并吧。

2017-11-28 10:03 UTC, zhaochao commented on trove/cluster/service.py
> +                               for instance in instances])
这里要排除 volume_size 为 None 的情况，同时如果所有 volume_size 都为空的话，min_volume_size 也为空。

```
volume_size_list = [instance['volume_size]'
                                for instance in instances
                                if instance['volume_size' is not none]
if len(volume_size_list) > 0:
    min_volume_size = min(volume_size_list)
else:
    min_volume_size = None
```

从代码逻辑看，我们不能排除有些 instance 设置了 volume ，有些没有的情况。

2017-11-28 10:03 UTC, zhaochao commented on trove/guestagent/datastore/experimental/mongodb/manager.py
> +                and backup_info:
用括号来实现分行比较好：
```
if ((cluster_config is None or 'shard_id' not in cluster_config)
        and backup_info):
```

2017-11-28 10:03 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +                        modules=modules_i)
减少了缩进的话，没必要一行一个 argument ，可以适当合并。

2017-11-28 10:25 UTC, zhaochao requested changes

2017-11-28 10:25 UTC, zhaochao commented on trove/cluster/service.py
> +                            if instance['volume_size' is not None]]
? 中括号不对。
`if instance['volume_size'] is not None`

2017-11-28 10:41 UTC, zhaochao approved these changes

2017-11-28 10:42 UTC, merged