MongoDB: resize the flavor of instance which is in replica-set.
eayunstack/trove pull request #67
Opened 2017-11-29 02:34 UTC by caisan

Allow user resize the flavor of instance that are the part of
a cluster. Only replica set allowed. Before this PR, try to
backup a instance, which belongs to a cluster will
raise exception:ClusterInstanceOperationNotSupported.
Same as supporting backup.

Fix: http://192.168.15.2/issues/11191

2017-11-29 02:55 UTC, fabian4 commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +        :return: True is replica-set, False is not.
return 描述信息有误?

2017-11-29 02:55 UTC, fabian4 commented on trove/instance/models.py
> +            cluster = DBCluster.load(self.context,self.db_info.cluster_id)
self.context,self.db_info.cluster_id 格式,中间空格?

2017-11-29 02:55 UTC, fabian4 commented on trove/instance/models.py
> + +          cluster can execute backup. other cluster's instance cannot.
能否改为, "Support MongoDB replica-set  instance execute backup." ?

2017-11-29 02:58 UTC, fabian4 commented
commit 信息能否提炼, 如:
Fix xxxxxx

Add   xxxxx

Change  xxxxx

2017-11-29 03:02 UTC, caisan commented on trove/instance/models.py
> + +          cluster can execute backup. other cluster's instance cannot.
typo. 应该把backup改成resize.

2017-11-30 03:43 UTC, caisan commented
```from trove.cluster.models import Cluster as DBCluster```需要使用local import?

2017-11-30 04:27 UTC, zhaochao requested changes
commit message 有不少地方要改一下：

> MongoDB: resize flavor instance in replica set
> 
> Enable user resize the flavor of instance that are the part of
> a cluster. Only enabled for MongoDB replica set. Before this, try to
> backup a instance, which belongs to a cluster will raise
> ception:ClusterInstanceOperationNotSupported.
> 
> Fix: http://192.168.15.2/issues/11191

第一行：应该大概是： MongoDB: support resizing flavor of a instance in replica set ；

Enable user resize -> Enables use to resize

the flavor of instance -> the flavor of a instance

a part of cluster -> a part of replica set cluster

Only enabled for MongoDB replica set. -> Currently this is only supported by MongoDB replica set.

ception: -> exception:

Fix: -> Fixes:

2017-11-30 04:27 UTC, zhaochao commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +    def allow_resize_flavor(self):
只是 resize_flavor ，resize_volume 不支持？

2017-11-30 04:27 UTC, zhaochao commented on trove/instance/models.py
> +from trove.cluster.models import Cluster as DBCluster
是，要用 local import ，这个文件有一个现成的例子，在 L625 。

2017-11-30 04:27 UTC, zhaochao commented on trove/instance/models.py
> +            cluster = DBCluster.load(self.context,self.db_info.cluster_id)
[bad-whitespace] Exactly one space required after comma [python/pylint]

2017-11-30 04:55 UTC, caisan commented on trove/common/strategies/cluster/experimental/mongodb/api.py
> +    def allow_resize_flavor(self):
@zhaochao 只是flavor.

2017-11-30 06:24 UTC, zhaochao requested changes
commit message 里 Fix: 也改成 Fixes: ，这样比较统一。

看了下 resize_flavor 的实现，目前看不出来会直接影响 replica set 的原因，改完剩下几个小问题可以先合并。

2017-11-30 06:24 UTC, zhaochao commented on trove/instance/models.py
> +
无关改动？

2017-11-30 07:10 UTC, merged